<a href="https://colab.research.google.com/github/philorfa/Biodata/blob/main/EnsambleWorld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#@title
from __future__ import absolute_import, division, print_function, unicode_literals # legacy compatibility

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import to_categorical
from time import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import ndarray
import skimage as sk
from skimage import transform
from skimage import util
#@title
!pip install --upgrade pyswarm
!pip install pymc3
!pip install --upgrade pactools

from sklearn.model_selection import train_test_split
from pyswarm import pso
from os import path
import os
import requests
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import numpy
import sys
import numpy as np
from numpy import loadtxt
from numpy import array
from numpy.random import choice
import pandas as pd
import time
import random
import statistics
import pandas
import math
import csv
import random
import logging
from pymc3 import *
import pymc3 as pm
from functools import reduce
from operator import add
from tqdm import tqdm
import geopy.distance
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from theano import shared
from sklearn import preprocessing
print('Running on PyMC3 v{}'.format(pm.__version__))
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Conv1D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Activation
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import layers
from tensorflow import keras
import tensorflow
from tensorflow.keras import datasets, layers, models
from keras.utils import np_utils

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.ticker import MaxNLocator

#TESNORFOW
import tensorflow as tf
from tensorflow import keras
from keras import datasets, layers, models
#KERAS LIBRARIES
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout , Flatten,BatchNormalization,Conv2D,MaxPooling2D, Activation,LSTM,Embedding,Input,GlobalAveragePooling2D
from keras.regularizers import l1, l2, l1_l2
from keras.callbacks import EarlyStopping, ModelCheckpoint,ReduceLROnPlateau
from keras import backend 
from keras.utils import np_utils

from numpy import savetxt

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from numpy import argmax

Requirement already up-to-date: pyswarm in /usr/local/lib/python3.7/dist-packages (0.6)
Requirement already up-to-date: pactools in /usr/local/lib/python3.7/dist-packages (0.3.1)
Running on PyMC3 v3.11.2


In [3]:
Test_data = pd.read_csv('/content/drive/MyDrive/Biodata/Datas/World/X_test_Wor.csv')
Test_data = Test_data.drop(['Unnamed: 0'],axis=1)

Test_labels = pd.read_csv('/content/drive/MyDrive/Biodata/Datas/World/y_test_Wor.csv')
Test_labels = Test_labels.drop(['Unnamed: 0'],axis=1)

In [4]:
print("Shape X_test:", Test_data.shape)
print("Shape y_test:", Test_labels.shape)

Shape X_test: (17093, 64)
Shape y_test: (17093, 1)


In [5]:
for i in range(len(Test_labels)):
  if (Test_labels['Depression_Score'][i]<=7.0):
    Test_labels['Depression_Score'][i]=0
  elif (Test_labels['Depression_Score'][i]<=12.0):
    Test_labels['Depression_Score'][i]=1
  else:
    Test_labels['Depression_Score'][i]=2

In [34]:
MLP = keras.models.load_model('/content/drive/MyDrive/Biodata/Datas/World/Models_class/model_mlp-4-0.615-0.808')
CNN =  keras.models.load_model('/content/drive/MyDrive/Biodata/Datas/World/Models_class/model_cnn-5-0.615-0.804')

MLP_2ND = keras.models.load_model('/content/drive/MyDrive/Biodata/Datas/World/Models_class/model_mlp-2-0.613-0.82')
CNN_2ND = keras.models.load_model('/content/drive/MyDrive/Biodata/Datas/World/Models_class/model_cnn-4-0.613-0.816')

In [12]:
img_rows, img_cols = 8,8

Test_data_cnn=np.array(Test_data)
Test_data_cnn = Test_data_cnn.reshape(Test_data.shape[0], img_rows, img_cols, 1)

input_shape = (img_rows, img_cols, 1)

Test_data_cnn = Test_data_cnn.astype('float32')

print('x_train shape:', Test_data_cnn.shape)
print(Test_data_cnn.shape[0], 'train samples')

x_train shape: (17093, 8, 8, 1)
17093 train samples


In [10]:
pred_mlp=MLP.predict_classes(Test_data)
cm = confusion_matrix(Test_labels, pred_mlp)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(Test_labels, pred_mlp))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


[0.71932953 0.45629908 0.67851431]
              precision    recall  f1-score   support

         0.0       0.65      0.72      0.68      5608
         1.0       0.49      0.46      0.47      5858
         2.0       0.70      0.68      0.69      5627

    accuracy                           0.62     17093
   macro avg       0.61      0.62      0.62     17093
weighted avg       0.61      0.62      0.61     17093



In [13]:
pred_cnn=CNN.predict_classes(Test_data_cnn)
cm = confusion_matrix(Test_labels, pred_cnn)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(Test_labels, pred_cnn))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


[0.63373752 0.49556163 0.71796695]
              precision    recall  f1-score   support

         0.0       0.69      0.63      0.66      5608
         1.0       0.48      0.50      0.49      5858
         2.0       0.68      0.72      0.70      5627

    accuracy                           0.61     17093
   macro avg       0.62      0.62      0.62     17093
weighted avg       0.62      0.61      0.61     17093



In [35]:
prob_mlp=MLP.predict(Test_data)
prob_cnn=CNN.predict(Test_data_cnn)
prob_mlp_2=MLP_2ND.predict(Test_data)
prob_cnn_2=CNN_2ND.predict(Test_data_cnn)

In [39]:
pred_ensabmle=[]
for i in range(len(prob_mlp)):
  pred_ensabmle.append(argmax(prob_mlp[i]+prob_cnn[i]+prob_mlp_2[i]+prob_cnn_2[i]))
pred_ensabmle=np.array(pred_ensabmle)

cm = confusion_matrix(Test_labels, pred_ensabmle)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print(cm.diagonal())
print(classification_report(Test_labels, pred_ensabmle))

[0.68830243 0.4720041  0.69521948]
              precision    recall  f1-score   support

         0.0       0.67      0.69      0.68      5608
         1.0       0.49      0.47      0.48      5858
         2.0       0.70      0.70      0.70      5627

    accuracy                           0.62     17093
   macro avg       0.62      0.62      0.62     17093
weighted avg       0.61      0.62      0.62     17093

